### ISSUE TITLE
Các lỗi cơ bản

### ISSUE THREAD

**Issue by manhtukhang** [yehnkay/VN_IME#1]
- Không Undo khi gặp phải kí tự có dấu
- Bỏ dấu sai các từ như:
`` bứơng bỉnh,  
bình thuờng,  
khó hỉêu, 
đột qụy  
``
- Khi gõ `uo + w` không ra `ương` mà ra `uơng`

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Đã gõ được như mô tả. Vẫn không undo được khi gặp phải ký tự có dấu

**Comment by khanhicetea** [comment]
Tắt (F2) thì Undo được :smile: Có cách nào trigger auto off khi Undo rồi tự động mở lại thì tốt :D

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Chào bạn, thanks bạn đã góp ý. Mình sẽ xem xét đề nghị này.

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Chào bạn, các chức năng như undo, redo, paste hiện đã có thể dùng như bình thường nhé, hi vọng bạn thích.

Chúc vui.
