### ISSUE TITLE
Thêm setting chuyển đổi bộ gõ (VNI <=> TELEX) vào menu

### ISSUE THREAD

**Issue by tarzanjw** [yehnkay/VN_IME#10]
Việc thay đổi file setting khá phức tạp và mất công, bạn có thể thêm 1 mục menu vào trong Preferences hoặc tạo ra 1 config ở global mà có thể dễ dàng chỉnh sửa trong Setting - User không?

Chẳng hạn như:

```
{
    "vn_ime_mode": "telex|vni",
}
```

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Chào bạn, mình đã chỉnh lại phần đọc setting. Để gõ kiểu TELEX, bạn thêm mục "telex" với giá trị "true" (không có dấu nháy đôi) vào phần Settings - User

**Comment by tarzanjw** [comment]
Cám ơn bạn, clear hơn nhiều rồi. Package ngon lắm.

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Tks ban
