### ISSUE TITLE
Package crash lúc gõ Tiếng Việt trong layout view nhiều cột của Sublime Text 3

### ISSUE THREAD

**Issue by vdhan** [yehnkay/VN_IME#13]
Từ menu Sublime Text chọn View -> Layout -> Columns: 2
Bật VN IME, gõ Tiếng Việt -> crash

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Hi ban, minh co thu reproduce issue nhung khong dc, vi du nhu [anh](https://goo.gl/photos/ugeMFCVeQudRNhKu9) nay, layout 2 columns hay grid 4 deu binh thuong ca, ban co the cung cap them thong tin duoc khong. (sr vi tieng viet khong dau)

**Comment by vdhan** [comment]
![84ce8da6-f86a-11e6-9c59-7f54265b054d](https://cloud.githubusercontent.com/assets/3064758/23182753/3ef48f0a-f8ac-11e6-8e3b-08e178dbffb2.png)
Lỗi như hình trên

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Hi ban, minh vua fix lai bug nay, ban thu lai xem nhe.

**Comment by vdhan** [comment]
Mình fix bug này như thế nào?

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Do nhiều views nên nó hơi rối về mặt input, mình đổi hàm on_modified thành on_modified_async là được

**Comment by vdhan** [comment]
Cám ơn bạn!
