### ISSUE TITLE
Không gõ telex được, gõ VNI thì được. Đã có thêm "telex": true

### ISSUE THREAD

**Issue by chiendo1010** [yehnkay/VN_IME#14]
Chào VN_IME, 
Hiện tại tôi đang bị trường hợp gõ VNI tốt, nhưng gõ telex không được dù đã thêm "telex": true trong Setting-User. Và có khởi động lại Sublime Text.
![screenshot from 2017-03-25 08-40-03](https://cloud.githubusercontent.com/assets/11450937/24318367/a9685b94-1136-11e7-9544-faa8f54fbde4.png)

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Chào bạn, mình thêm setting này trong file `.config/sublime-text-3/Packages/User/Preferences.sublime-settings`, nhấn F2 2 lần để restart plugin và không cần restart sublime

Khi save file setting, trong logconsole sẽ có dòng `reloading settings Packages/User/Preferences.sublime-settings`. Bạn thử check lại xem.
![2017-03-25-085950_1917x401_scrot](https://cloud.githubusercontent.com/assets/9514491/24318570/17a8aa98-113a-11e7-9684-736f8486fed0.png)

**Comment by chiendo1010** [comment]
Mình đang bị trường hợp là không gõ được bằng  kiểu Telex, gõ VNI thì được. Mình có thêm dòng "telex": true, như trong hình rồi nhưng vẫn không gõ được. 

.

**Comment by chiendo1010** [comment]
Mình đã chỉnh được. Lần đầu mình thêm vào bằng cách: Preference / Package Setting / Package Control / Setting - User.

Rồi thêm dòng "telex": true. Nhưng kết quả gõ vẫn là VNI được, Telex thì gõ không được.

Mò mò 1 hồi thì vào Preference / Setting thì không thấy dòng: "telex": true, nên thêm vào.

Ra gõ được vài chữ tiếng Việt bằng Telex, sau đó không gõ tiếp được. Restart Sublime vẫn không được.

Rồi install VN IME lại. Kết quả giờ gõ được tốt bằng Telex.

Solved!
