### ISSUE TITLE
Lỗi gõ chữ.

### ISSUE THREAD

**Issue by chiendo1010** [yehnkay/VN_IME#15]
Khi tôi gõ từ giá, như lúc nào cũng hiện thị từ: gi'a.

![screenshot from 2017-03-26 11-59-49](https://cloud.githubusercontent.com/assets/11450937/24328721/c26a2254-121b-11e7-86f6-7bb4cf5a1e87.png)

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
vấn đề này do framework bogo, waiting for them

**Comment by chiendo1010** [comment]
Ngoài ra khi gõ chữ in hoa thì không gõ được một số chứ: Ví dụ: TẮC và ĐẾM thì sẽ không được.

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
sorry ban, hien tai minh khong su dung sublime text va plugin nay nua, nen minh khong maintain repo nay duoc. Neu ban thay co the duy tri tiep repo nay va co hung thu co the lien he lai tui minh,

tks you

**Comment by vdhan** [comment]
Mình muốn duy trì repo này vì hiện nay, plugin để viết Tiếng Việt không nhiều. Bạn có thể liên hệ với mình qua email: anvudh@gmail.com

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Hi @vdhan ban co the xem xet nguyen do bug ma @chiendo1010 report ko? co cach de fix duoc ko?

**Comment by vdhan** [comment]
@88d52bdba0366127fffca9dfa93895: Mình dùng bogo-engine thì thấy viết bình thường (Trên Linux mình dùng Bogo thay vì Unikey). Mình đang xem code của VN IME thế nào.
Edit: Sau khi mình tìm hiểu sơ lược thì có vài vấn đề sau:
1. Vì 1 lí do nào đó, command starttime chạy đến 2 lần, việc này dẫn đến khi chạy hàm process_sequence của bogo, lúc ta truyền vào process_sequence('giá') kết quả nhận được là gía (bug từ bạn @chiendo1010 report). Nên mình đề xuất 1 vài solution sau:
a. Tìm cách để chỉ gọi command starttime 1 lần mỗi lần modify.
b. Mỗi lần gọi đến method process của class StartimeCommand, mình nên làm thêm bước chuyển variable word thành raw input sequence (ví dụ "giá" thành "gias") trước khi gọi đến hàm process_sequence của bogo.
2. Hiện tại code mình đang theo hướng dùng API bắt sự kiện OnModified và thay thế từ trong selection của Sublime, nên gặp phải vấn đề khi paste 1 số từ tiếng Anh ví dụ như chaos, plugin VN IME sẽ tự chuyển thành cháo. Không biết bạn có hướng giải quyết nào cho vấn đề này không?

**Comment by hailoc12** [comment]
Rất cám ơn tác giả đã tạo ra bộ gõ này. Trong quá trình sử dụng mình thấy một số điểm còn cần cải tiến, vì vậy đã mạnh dạn sửa code để tạo ra một phiên bản hoàn thiện hơn. Vì không biết làm thế nào để pull request tại repository này nên mình up lên tại đây: https://github.com/hailoc12/Improved-VN-IME-for-Sublime-Text
Trong phiên bản này, mình có triển khai hai vấn đề mà bác @vdhan đã đưa ra ở trên (ý tưởng 1a, 1b). Vấn đề bác @chiendo1010 có thể giải quyết được trong thời gian tới.

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Tks bạn @hailoc12 đã cố gắng fix những lỗi này, bạn có thể tham khảo link [này](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) để tạo PR. Bên fork của bạn mình không thấy file `.py`, có mỗi file binary `Vn Ime.sublime-package`, nên mình chưa review được.

Regards,

**Comment by hailoc12** [comment]
Cám ơn bạn, mình sẽ tạo pull request. File Vn Ime.sublime-package là dạng zip, có thể giải nén để xem các file .py trong đó

**Comment by chiendo1010** [comment]
Upgrade lên Ubuntu 18.04 xài bộ gõ tích hợp trong hệ điều hành sẵn luôn, không còn xảy ra bug này nữa.

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Tks for your closing, just 6 years but thank you @chiendo1010 . :D

**Comment by chiendo1010** [comment]
> Tks for your closing, just 6 years but thank you @chiendo1010 . :D

Sorry about that!
