### ISSUE TITLE
Dấu ở cuối từ

### ISSUE THREAD

**Issue by tarzanjw** [yehnkay/VN_IME#2]
Cám ơn bạn  nhé, cái này giúp mình nhiều lắm.

Có 1 sự bất tiện nho nhỏ ở đây, một số từ có dấu ở cuối, như *hòa* thì plugin đang để dấu là *hoà*. Bạn có thể chỉnh được không?

Nếu bằng cách nào đó tích hợp hẳn IBus vào được thì tốt quá.

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Đã gõ được như mô tả
