### ISSUE TITLE
Chuyển đổi tiếng việt lúc dán từ clipboard

### ISSUE THREAD

**Issue by anhskohbo** [yehnkay/VN_IME#6]
Hệ thống bắt luôn sự kiện để chuyển đổi tiếng việt lúc dán clipboard.
Ví dụ copy `header` và dán lại sẽ thành `headẻ`.

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Mình cũng gặp tình trạng này, cách giải quyết tạm thời là tắt plugin rồi paste clipboard và bật lại plugin
