### ISSUE TITLE
Sử dụng bogo-python làm backend

### ISSUE THREAD

**Issue by lewtds** [yehnkay/VN_IME#7]
[bogo-python](https://github.com/BoGoEngine/bogo-python) là một thư viện xử lý đặt dấu tiếng Việt tách ra từ dự án [ibus-ringo](http://ngochin.com/ibus-ringo) và đã được test kỹ càng. Nó có thể xử lý được hết các trường hợp lỗi trong issue #1, #2, #3, #4, #5.

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Phiên bản 2 của plugin đã được viết lại dựa trên bogo-python
