### ISSUE TITLE
Thanks bạn nhiều, bạn là cứu tin của mình... nhưng gõ unikey chưa được chuẩn lắm.

### ISSUE THREAD

**Issue by badromance007** [yehnkay/VN_IME#8]
Ví dụ: gõ chữ "tường"
--> Unikey : tuwowngf, tuowngf, tuongwf 
--> của bạn chỉ gõ được : tuwowngf

 hay có một vài trường hợp chữ sẽ bị nhỏ khi có dấu vd: gõ chữ "tiền"
--> Unikey: tiền
--> của bạn: tiền ( chữ "ề" bị nhỏ lại )

....

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Đã gõ được chữ "tường" với các trường hợp trên. Trường hợp chữ bị nhỏ lại mình nghĩ do Sublime Text như vậy.
