### ISSUE TITLE
Không gõ được chữ Đ hoa và nghĩ/nghĩa

### ISSUE THREAD

**Issue by superthin** [yehnkay/VN_IME#9]
Sao không mượn bộ gõ có sẵn trên máy đưa vào mà tự định nghĩa bộ gõ riêng nhỉ? Kết quả là mình không gõ được chữ Đ hoa và chữ nghĩ, nghĩa.

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Đã gõ được chữ Đ hoa và chữ nghĩ, nghĩa
